// Generated by CoffeeScript 1.6.2
define(["backbone"], function(Backbone) {
  var LabelsView;

  return LabelsView = Backbone.View.extend({
    render: function(index) {
      var $ordered_list,
        _this = this;

      $ordered_list = $("<ol/>");
      _.chain(this.collection).sortBy(function(item) {
        return item.positions[index];
      }).each(function(item) {
        return $ordered_list.append(_this._render_item(item));
      });
      return this.$el.html($ordered_list);
    },
    _render_item: function(item) {
      return $("<li/>", {
        text: item.label
      });
    }
  });
});
